apiVersion: apps/v1
kind: Deployment
metadata:
  name: housing-frontend
  namespace: mlops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: housing-frontend
  template:
    metadata:
      labels:
        app: housing-frontend
    spec:
      containers:
      - name: frontend
        image: saimanasg/housing-frontend:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: housing-frontend
  namespace: mlops
spec:
  selector:
    app: housing-frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30100
  type: NodePort
